<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Program extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'name',
        'type',
        'career',
        'credits_required'
    ];

    protected $dates = [
        'deleted_at',
        'updated_at'
    ];

    public function plansOfStudy()
    {
        return $this->belongsToMany('PlanofStudy');
    }

    public function degreeRequirements()
    {
        return $this->hasMany('DegreeRequirement');
    }

    public function scopeRecent($query)
    {
        return $query->orderBy('updated_at', 'desc')->take(5);
    }

    public function setUpdatedAt($value)
    {
        return parent::setUpdatedAt($value); // TODO: Change the autogenerated stub
    }

    public function getUpdatedAtAttribute()
    {
        return date('g:i A n/j/Y', strtotime($this->attributes['updated_at'])); // TODO: Change the autogenerated stub
    }
}
